export enum NotificationType {
  NEW_CONTENT = "new_content",
  LEARNING_REMINDER = "learning_reminder",
  SUBSCRIPTION_RENEWAL_REMINDER = "subscription_renewal_reminder",
  SUBSCRIPTION_EXPIRED = "subscription_expired",
  SUBSCRIPTION_PAYMENT_SUCCESS = "subscription_payment_success",
  SUBSCRIPTION_PAYMENT_FAILURE = "subscription_payment_failure",
  ACTIVATION_CODE_REDEEMED = "activation_code_redeemed",
  UNIVERSITY_INFO_CHANGE_REQUEST_UPDATE = "university_info_change_request_update",
  PASSWORD_CHANGED = "password_changed",
  STREAK_REMINDER = "streak_reminder",
  DAILY_REVISION = "daily_revision",
  SYSTEM_ALERT = "system_alert",
  GENERAL = "general",
  REMINDER = "reminder",
  WELCOME = "welcome",
  OTHERS = "others",
}
